global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:80"]

  - job_name: "order-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:80"]

  - job_name: "payment-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["payment-service:80"]

  - job_name: "notification-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["notification-service:80"]
